# Generated by Django 4.0.1 on 2022-02-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_description_product_image_product_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="external_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
